export default {
  Adjectives: [
    'Admiration',
    'Adorable',
    'Affectionate',
    'Afraid',
    'Aggravate',
    'Aggressive',
    'Agitated',
    'Alarm',
    'Alive',
    'Angry',
    'Annoyed',
    'Anticipate',
    'Anxiety',
    'Appreciated',
    'Arrogance',
    'Ashamed',
    'Authoritative',
    'Aversion',
    'Awe',
    'Awful',
    'Belligerent',
    'Bitter',
    'Blue',
    'Blunt',
    'Bold',
    'Bored',
    'Brilliant',
    'Bullying',
    'Callous',
    'Cautious',
    'Cheerful',
    'Clever',
    'Combative',
    'Comical',
    'Compassionate',
    'Contemptuous',
    'Content',
    'Contrary',
    'Cool',
    'Cordial',
    'Covetous',
    'Cross',
    'Cruelty',
    'Curious',
    'Dainty',
    'Defeated',
    'Defiant',
    'Dejected',
    'Delighted',
    'Despair',
    'Devoted',
    'Disagreeable',
    'Disciplined',
    'Discontent',
    'Disgust',
    'Distaste',
    'Doubtful',
    'Dread',
    'Dutiful',
    'Dynamic',
    'Elated',
    'Enraged',
    'Envy',
    'Evil',
    'Excited',
    'Exhausted',
    'Exhilaration',
    'Exuberance',
    'Fearful',
    'Fearless',
    'Feisty',
    'Fierce',
    'Flattered',
    'Folksy',
    'Forgiving',
    'Forlorn',
    'Frustrated',
    'Furious',
    'Fury',
    'Gay',
    'Generous',
    'Gentle',
    'Glee',
    'Grateful',
    'Greedy',
    'Happy',
    'Harsh',
    'Hatred',
    'Haughty',
    'Heroic',
    'Honest',
    'Honored',
    'Hope',
    'Horror',
    'Hostile',
    'Hunch',
    'Ignored',
    'Imaginative',
    'Impartial',
    'Impatient',
    'Inconsiderate',
    'Indifferent',
    'Innocent',
    'Inquisitive',
    'Insensitivity',
    'Insightful',
    'Inspired',
    'Intolerance',
    'Intuitive',
    'Ire',
    'Irritate',
    'Isolated',
    'Jealous',
    'Joy',
    'Kind',
    'Kindred',
    'Lazy',
    'Lively',
    'Lonely',
    'Love',
    'Lucky',
    'Mad',
    'Malice',
    'Mean',
    'Meek',
    'Melancholy',
    'Mollified',
    'Nasty',
    'Natural',
    'Naughty',
    'Nervous',
    'Obnoxious',
    'Obstinate',
    'Outraged',
    'Outstanding',
    'Overjoyed',
    'Pain',
    'Panic',
    'Patient',
    'Perky',
    'Perturb',
    'Pity',
    'Powerful',
    'Pride',
    'Querulous',
    'Rage',
    'Rapturous',
    'Relaxed',
    'Reliable',
    'Relief',
    'Reluctant',
    'Repentant',
    'Repulsive',
    'Resent',
    'Resigned',
    'Resistant',
    'Restrained',
    'Reverent',
    'Revulsion',
    'Ridiculed',
    'Rough',
    'Rude',
    'Sad',
    'Satisfy',
    'Scornful',
    'Severe',
    'Shame',
    'Sick',
    'Silly',
    'Sixthsense',
    'Skill',
    'Sorrow',
    'Spite',
    'Stubborn',
    'Sure',
    'Surprise',
    'Sweet',
    'Tame',
    'Tempted',
    'Tender',
    'Tense',
    'Terse',
    'Tired',
    'Trepidation',
    'Uncertain',
    'Unhappy',
    'Valiant',
    'Victorious',
    'Vindictive',
    'Violent',
    'Vocal',
    'Wary',
    'Weary',
    'Weird',
    'Wicked',
    'Wise',
    'Woeful',
    'Worrier',
    'Worthy',
    'Wrath',
  ],
  Nature: [
    'Abundant',
    'Animism',
    'Aquatic',
    'Arctic',
    'Array',
    'Autumn',
    'Awareness',
    'Barren',
    'Beauty',
    'Bees',
    'Biodegradable',
    'Boulder',
    'Bountiful',
    'Brilliant',
    'Brook',
    'Buoyancy',
    'Butte',
    'Butterfly',
    'Buzz',
    'Celestial',
    'Cliff',
    'Climate',
    'Clouds',
    'Coastal',
    'Color',
    'Combustible',
    'Commercial',
    'Commune',
    'Conifer',
    'Conservation',
    'Conspicuous',
    'Contiguous',
    'Cordillera',
    'Cosmography',
    'Crater',
    'Crucial',
    'Current',
    'Deft',
    'Demise',
    'Deplorable',
    'Desert',
    'Destructive',
    'Disposable',
    'Dynamic',
    'Earthquake',
    'Earthy',
    'Eclipse',
    'Ecological',
    'Efficient',
    'Electrifying',
    'Endangered',
    'Endemic',
    'Enigmatic',
    'Environment',
    'Erosion',
    'Escarpment',
    'Esker',
    'Evergreen',
    'Exclusive',
    'Fall',
    'Fallow',
    'Farming',
    'Fertile',
    'Fibrous',
    'Fierce',
    'Flood',
    'Fog',
    'Foliage',
    'Forest',
    'Glacier',
    'Gorgeous',
    'Grassland',
    'Gravity',
    'Growth',
    'Gust',
    'Habitat',
    'Hail',
    'Healthy',
    'Hibernate',
    'Horizon',
    'Hurricane',
    'Hygienic',
    'Iceberg',
    'Imitation',
    'Indigenous',
    'Innate',
    'Intense',
    'Intimate',
    'Juniper',
    'Keen',
    'Land',
    'Landform',
    'Leaves',
    'Logging',
    'Magical',
    'Magnificence',
    'Magnificent',
    'Marine',
    'Massif',
    'Meteor',
    'Migratory',
    'Mimesis',
    'Moon',
    'Mountains',
    'Mushroom',
    'Nascent',
    'Native',
    'Natural',
    'Nature',
    'Neglected',
    'Nurture',
    'Organism',
    'Original',
    'Pantheism',
    'Parasitic',
    'Passionate',
    'Peaceful',
    'Peaks',
    'Pinnacle',
    'Planet',
    'Pollutant',
    'Popular',
    'Prairie',
    'Predator',
    'Preservation',
    'Pristine',
    'Productive',
    'Protection',
    'Quiet',
    'Radioactive',
    'Range',
    'Renewable',
    'Representation',
    'Reproductive',
    'Reserve',
    'Resilient',
    'Resources',
    'Restorative',
    'Ridge',
    'River',
    'Rock',
    'Rotting',
    'Safe',
    'Sanctuary',
    'Sane',
    'Scenic',
    'Season',
    'Sediment',
    'Serene',
    'Serenity',
    'Shelter',
    'Shore',
    'Smells',
    'Snow',
    'Solar',
    'Soluble',
    'Sounds',
    'Spatial',
    'Splendid',
    'Spring',
    'Staunch',
    'Stream',
    'Stunning',
    'Taint',
    'Tarn',
    'Temperate',
    'Terrain',
    'Toxic',
    'Tropical',
    'Tsunami',
    'Typical',
    'Ultimate',
    'Undeveloped',
    'Unique',
    'Uplifting',
    'Uproot',
    'Value',
    'Variety',
    'Versatile',
    'Visible',
    'Vista',
    'Volcano',
    'Vulnerable',
    'Warmth',
    'Weather',
    'Wildlife',
    'Winter',
    'Worldwide',
  ],
  Things: [
    'Wheel',
    'Aeroplane',
    'Lightbulb',
    'Internet',
    'PC',
    'Telephone',
    'Penicillin',
    'Smartphone',
    'Toilet',
    'Combustionengine',
    'Washingmachine',
    'Centralheating',
    'Fridge',
    'Painkillers',
    'Steamengine',
    'Freezer',
    'Camera',
    'Cars',
    'Spectacles',
    'Toiletpaper',
    'Train',
    'Google',
    'Microwave',
    'Email',
    'Hotwater',
    'Shoes',
    'Compass',
    'Ibuprofen',
    'Toothbrush',
    'Laptop',
    'Knife',
    'Scissors',
    'Paper',
    'Spacetravel',
    'Kettle',
    'Calculator',
    'Bed',
    'Remotecontrol',
    'Roof',
    'Airconditioning',
    'Wi-Fi',
    'Cats-eyes',
    'Matches',
    'Bicycle',
    'Teabags',
    'Umbrella',
    'Taps',
    'Helmet',
    'Watch',
    'eBay',
    'DVDplayer',
    'Ladder',
    'Sunscreen',
    'Lawnmower',
    'Make-up',
    'Chair',
    'Sunglasses',
    'Football',
    'Bread',
    'Sofa',
    'Razorblades',
    'Screwdriver',
    'Motorways',
    'Headphones',
    'Towels',
    'Push-upbra',
    'Binoculars',
    'Mascara',
    'Hairdryer',
    'Facebook',
    'Escalator',
    'Hairdye',
    'Wellingtonboots',
    'Spellcheck',
    'Calendars',
    'Cheese',
    'Post-itnotes',
    'Gloves',
    'Satellite',
    'Pedestriancrossing',
    'Curtains',
    'Bottleopener',
    'Foodblender',
    'Brush',
  ],
  Technology: [
    'Algebra',
    'Adjacent',
    'Algorithm',
    'Acceleration',
    'Altitude',
    'Arctan',
    'Asymptote',
    'Binomial',
    'Calculus',
    'Cardinality',
    'Circle',
    'Coefficient',
    'Complex Numbers',
    'Compute',
    'Concave',
    'Conjugate',
    'Convex',
    'Coordinates',
    'Cosine',
    'CrossProduct',
    'Cylinder',
    'Denominator',
    'Derivative',
    'Diameter',
    'Difference',
    'Dilation',
    'Dimensions',
    'Ellipse',
    'Equation',
    'Exponent',
    'Factorial',
    'Fibonacci Sequence',
    'Geometry',
    'Gravity',
    'Infinite',
    'Interval',
    'Inverse',
    'Limit',
    'Logarithm',
    'Matrix',
    'Minute',
    'Moment',
    'Modular Arithmetic',
    'Multiplication',
    'OddNumber',
    'Polar Axis',
    'Polynomial',
    'Pascals Triangle',
    'PrimeNumber',
    'Quadratic Equation',
    'Radian',
    'Reflection',
    'Residual',
    'Scalar Product',
    'Sphere',
    'Speed',
    'Series',
    'Symmetric',
    'Sum',
    'Square',
    'Trigonometry',
    'Union',
    'Pythagorean Theorem',
    'Abutment',
    'Activation',
    'Amplitude',
    'Analysis',
    'Angle',
    'Assembly',
    'Automation',
    'Axis',
    'Axle',
    'Balance',
    'Battery',
    'Bearing',
    'Blueprint',
    'Building',
    'Calculation',
    'Cantilever',
    'Cell',
    'Circumference',
    'Combustion',
    'Communication',
    'Component',
    'Compress',
    'Concept',
    'Constriction',
    'Construction',
    'Consultation',
    'Control',
    'Conversion',
    'Conveyance',
    'Conveyorbelt',
    'Cooling',
    'Coupling',
    'Crank',
    'Current',
    'Curves',
    'Degree',
    'Depth',
    'Design',
    'Device',
    'Diagram',
    'Diesel',
    'Dimension',
    'Direction',
    'Distill',
    'Distribution',
    'Elastic',
    'Electrical',
    'Electronics',
    'Element',
    'Energy',
    'Engine',
    'Excavation',
    'Expert',
    'Fabrication',
    'Flexible',
    'Flow',
    'Fluid',
    'Fluorescent',
    'Force',
    'Frame',
    'Friction',
    'Fuel',
    'Fulcrum',
    'Gear',
    'Generate',
    'Generator',
    'Gimbals',
    'Grade',
    'Grading',
    'Hardware',
    'Heat',
    'Hoist',
    'Horizontal',
    'Hydraulic',
    'Illumination',
    'Information',
    'Injection',
    'Installation',
    'Instrument',
    'Intersection',
    'Joint',
    'Lever',
    'Lift',
    'Liquid',
    'Load',
    'Machine',
    'Management',
    'Manufacturing',
    'Mark',
    'Measurement',
    'Mechanize',
    'Modular',
    'Mold',
    'Motion',
    'Motor',
    'Negative',
    'Nuclear',
    'Object',
    'Operation',
    'Oscilloscope',
    'Physics',
    'Pivot',
    'Plumb',
    'Pneumatic',
    'Power',
    'Precision',
    'Process',
    'Production',
    'Project',
    'Propulsion',
    'Pulley',
    'Radiate',
    'Ream',
    'Refine',
    'Refrigeration',
    'Regulation',
    'Repair',
    'Retrofit',
    'Revolution',
    'Rotation',
    'Savvy',
    'Scheme',
    'Schooling',
    'Scientific',
    'Sequence',
    'Shape',
    'Slide',
    'Solar',
    'Stability',
    'Strength',
    'Structure',
    'Studying',
    'Superstructure',
    'Suspension',
    'Technology',
    'Tools',
    'Transform',
    'Transmission',
    'Transmit',
    'Turbine',
    'Vacuum',
    'Valve',
    'Vertical',
    'Vibration',
    'Weight',
    'Weld',
    'Withstand',
    'Worker',
  ],
  People: [
    'Pablo Picasso',
    'Vincent van Gogh',
    'Marilyn Monroe ',
    'Abraham Lincoln ',
    'Mother Teresa',
    'John F. Kennedy ',
    'Martin Luther King ',
    'Nelson Mandela ',
    'Queen Elizabeth II ',
    'Winston Churchill',
    'Donald Trump',
    'Bill Gates ',
    'Muhammad Ali ',
    'Mahatma Gandhi',
    'Margaret Thatcher ',
    'Christopher Columbus ',
    'Charles Darwin ',
    'Elvis Presley ',
    'Paul McCartney ',
    'Queen Victoria ',
    'Pope Francis ',
    'Jawaharlal Nehru ',
    'Leonardo da Vinci',
    'Vincent Van Gogh ',
    'Franklin D. Roosevelt ',
    'Pope John Paul II ',
    'Thomas Edison',
    'Rosa Parks ',
    'Oprah Winfrey',
    'Indira Gandhi',
    'Benazir Bhutto',
    'George Orwell',
    'Desmond Tutu ',
    'Dalai Lama',
    'Walt Disney',
    'Neil Armstrong',
    'Barack Obama',
    'Malcolm X',
    'J. K. Rowling',
    'Richard Branson',
    'Pelé',
    'Angelina Jolie',
    'Jesse Owens',
    'Ernest Hemingway',
    'John Lennon',
    'Henry Ford',
    'Haile Selassie',
    'Joseph Stalin',
    'Michael Jordon',
    'George Bush Jnr',
    'Vladimir Lenin',
    'Ingrid Bergman',
    'Leo Tolstoy',
    'Oscar Wilde',
    'Coco Chanel',
    'Charles de Gaulle',
    'Amelia Earhart',
    'Louis Pasteur',
    'Mikhail Gorbachev',
    'Plato ',
    'Adolf Hitler',
    'Sting',
    'Mary Magdalene',
    'Alfred Hitchcock',
    'Michael Jackson',
    'Madonna',
    'Cleopatra',
    'Grace Kelly',
    'Steve Jobs',
    'Ronald Reagan',
    'Lionel Messi',
    'Babe Ruth',
    'Bob Geldof',
    'Roger Federer',
    'Sigmund Freud',
    'Mao Zedong',
    'David Beckham',
    'Tiger Woods',
    'Usain Bolt',
    'Carl Lewis',
    'Prince Charles',
    'C.S. Lewis',
    'Billie Holiday',
    'J.R.R. Tolkien',
    'Anne Frank',
    'Marie Antoinette',
    'Cristiano Ronaldo',
    'Marie Curie',
    'Stephen Hawking',
    'Tim Berners Lee',
    'Shakira',
    'Tom Cruise',
    'Al Gore',
    'Sacha Baron Cohen',
    'George Clooney',
    'Paul Krugman',
    'Jimmy Wales',
    'Brad Pitt',
    'Kylie Minogue',
    'Malala Yousafzai',
    'Stephen King',
    'Justin Bieber',
    'Carl XVI Gustaf',
    'Johann Sebastian Bach',
    'Ludwig van Beethoven',
    'Wolfgang Amadeus Mozart',
    'Elvis Presley',
    'Elon Musk',
    'Albert Einstein',
    'Michael Faraday',
    'Galileo Galilei',
    'Isaac Newton',
    'Julius Caesar',
    'Napoleon',
    'Karl Marx',
    'Diego Maradona',
    'Vladimir Putin',
    'Grigorij Rasputin',
  ],
};
